export enum NotificationType {
    BOOKING_CREATED = 'BOOKING_CREATED',
    BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
    BOOKING_CANCELLED = 'BOOKING_CANCELLED',
    PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
    PAYMENT_FAILED = 'PAYMENT_FAILED',
    REVIEW_CREATED = 'REVIEW_CREATED',
    SERVICE_UPDATED = 'SERVICE_UPDATED',
    SERVICE_CREATED = 'SERVICE_CREATED',
    ADMIN_ANNOUNCEMENT = 'ADMIN_ANNOUNCEMENT',
    SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION'
}

export enum NotificationStatus {
    UNREAD = 'UNREAD',
    READ = 'READ',
    ARCHIVED = 'ARCHIVED'
} 